[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
minidb-engine = { path = "../minidb-engine" }
clap = { version = "4.0", features = ["derive"] }
rustyline = {version = "12", features = ["with-file-history"]}
shell-words = "1.1"
