[package]
name = "minidb-engine"
version = "0.1.0"
edition = "2021"
description = "minimalistic database engine"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rand = "*"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
