[package]
name = "visualization"
version = "0.1.0"
edition = "2021"


[dependencies]
minidb-engine = { path = "../minidb-engine" }
eframe = "0.30"
byteorder = "1.4"
serde = { version = "1.0", features = ["derive"]}
bincode = "1.3"

